# Generated by Django 3.1.1 on 2020-09-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_auto_20200912_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
