# Generated by Django 3.1.1 on 2020-09-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyManagement', '0001_initial'),
        ('StudentManagement', '0003_auto_20200912_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FacultyManagement.advisor'),
        ),
    ]
