# Generated by Django 3.1.1 on 2020-09-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyManagement', '0001_initial'),
        ('StudentManagement', '0004_student_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='FacultyManagement.advisor'),
        ),
    ]
