# Generated by Django 3.1.1 on 2020-09-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='images/logo/')),
                ('constitution', models.FileField(upload_to='files/constitution/')),
            ],
        ),
    ]
