# Generated by Django 3.1.1 on 2020-09-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentManagement', '0003_auto_20200912_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField()),
                ('street_address', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.student')),
            ],
        ),
    ]
